version: '2.1'

services:
  mysql2:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd123
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpwd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-umysqluser", "-pmysqlpwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
