server.port: 7003

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: mysqluser
    password: mysqlpwd
    hikari:
      initialization-fail-timeout: 60000

---
spring.profiles: docker


server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql2/review-db
